// Phase 10.5: generates a new level's starting skeleton -- every field
// content-lint (src/content/__tests__/contentLint.test.ts) actually checks,
// pre-filled with clearly-marked TODOs rather than left out, so a content
// author fills in prose instead of hunting through types.ts for what shape
// a level even needs. Not wired into any other script; run by hand.
//
// Usage:
//   node scripts/scaffold-level.mjs --id ch2-federation --chapter ch2 \
//     --order 15 --title "Separate Books, One Front Desk" \
//     --concept "Database Federation" --analogy "The Regional Ledger"
//
// Writes the skeleton to stdout by default; pass --write to append it to
// src/content/<chapter>-extra.ts instead (creating the file, with the
// import/export scaffolding, if it doesn't exist yet).

import { existsSync, appendFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const CONTENT_DIR = path.join(__dirname, '..', 'src', 'content')

function parseArgs(argv) {
  const args = {}
  for (let i = 0; i < argv.length; i++) {
    if (!argv[i].startsWith('--')) continue
    const key = argv[i].slice(2)
    if (key === 'write') {
      args.write = true
      continue
    }
    args[key] = argv[i + 1]
    i++
  }
  return args
}

function fail(message) {
  console.error(`error: ${message}`)
  process.exit(1)
}

function camelCase(id) {
  return id.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
}

function levelSkeleton({ id, chapterId, order, title, concept, analogy }) {
  const varName = camelCase(id)
  return `
// ---------------------------------------------------------------------------
// TODO: ${title} (${concept})
// ---------------------------------------------------------------------------
// Generated by scripts/scaffold-level.mjs -- every TODO below is checked by
// content-lint (src/content/__tests__/contentLint.test.ts); the file won't
// pass until they're all filled in with real prose.

const ${varName}StartGraph: SimGraph = { nodes: [client()], edges: [] }

const ${varName}: Level = {
  id: '${id}',
  chapterId: '${chapterId}',
  order: ${order},
  title: '${title}',
  realConcept: '${concept}',
  analogyName: '${analogy}',
  stages: [
    {
      kind: 'situation',
      title: 'TODO: situation title',
      body: [
        'TODO: 1-2 sentences setting up why this level exists in the delivery-company story.',
      ],
    },
    {
      kind: 'teach',
      title: 'TODO: teach title',
      body: [
        'TODO: explain ${concept} through the delivery-company analogy first, then name the real term.',
      ],
      readmeQuote: {
        text: 'TODO: verbatim quote from karanpratapsingh/system-design -- never paraphrased.',
        source: 'TODO: e.g. "Chapter I · ${concept}"',
      },
      realWorldExamples: ['TODO: at least one real system that does this'],
      check: {
        question: 'TODO: one comprehension-check question',
        options: [
          { id: 'a', label: 'TODO: correct option', correct: true, feedback: 'TODO: why this is right.' },
          { id: 'b', label: 'TODO: distractor', correct: false, feedback: 'TODO: why this is wrong.' },
        ],
      },
    },
    {
      kind: 'build',
      mode: 'guided',
      title: 'TODO: build stage title',
      brief: ['TODO: what the player is being asked to build and why.'],
      startingGraph: ${varName}StartGraph,
      unlockedKinds: ['client' /* TODO: add the new kind(s) this level unlocks */],
      workload: { durationMs: 6000, tickMs: 250, trafficCurve: constantTraffic(40) },
      slo: { maxP99Ms: 250, maxErrorRate: 0.01, minThroughputRps: 30 /* TODO: tune against the real numbers this graph produces */ },
      guidedSteps: [{ instruction: 'TODO: step-by-step build instructions.' }],
      debrief: {
        successBody: ['TODO: what just happened, and the lesson to take from it.'],
        failureBody: ['TODO: what likely went wrong and how to fix it.'],
        readmeQuote: {
          text: 'TODO: verbatim quote from karanpratapsingh/system-design.',
          source: 'TODO: e.g. "Chapter I · ${concept}"',
        },
        realWorldExamples: ['TODO: at least one real system that does this'],
        interviewPhrase: 'TODO: "one sentence, phrased the way you\\'d actually say it in an interview."',
        ruleOfThumb: 'TODO: one-sentence takeaway for the decision journal.',
      },
    },
  ],
  // TODO: at least 2 quiz questions, only surfaced once this level is completed.
  quizQuestions: [
    {
      id: 'q1',
      question: 'TODO',
      options: [
        { id: 'a', label: 'TODO: correct', correct: true, feedback: 'TODO' },
        { id: 'b', label: 'TODO: distractor', correct: false, feedback: 'TODO' },
      ],
    },
    {
      id: 'q2',
      question: 'TODO',
      options: [
        { id: 'a', label: 'TODO: correct', correct: true, feedback: 'TODO' },
        { id: 'b', label: 'TODO: distractor', correct: false, feedback: 'TODO' },
      ],
    },
  ],
}
`
}

function main() {
  const args = parseArgs(process.argv.slice(2))
  for (const required of ['id', 'chapter', 'title', 'concept']) {
    if (!args[required]) fail(`--${required} is required`)
  }
  if (!/^[a-z0-9]+-[a-z0-9-]+$/.test(args.id)) fail(`--id "${args.id}" should look like "ch2-federation"`)

  const skeleton = levelSkeleton({
    id: args.id,
    chapterId: args.chapter,
    order: args.order ?? '0 /* TODO: position within the chapter */',
    title: args.title,
    concept: args.concept,
    analogy: args.analogy ?? 'TODO: the delivery-company name for this',
  })

  if (!args.write) {
    console.log(skeleton)
    console.log(
      `\n// Not written to disk -- pass --write to append to src/content/${args.chapter}-extra.ts, or paste this into an existing chapter file yourself (remember to add the const to that file's exported *_LEVELS array).`,
    )
    return
  }

  const targetFile = path.join(CONTENT_DIR, `${args.chapter}-extra.ts`)
  if (!existsSync(targetFile)) {
    writeFileSync(
      targetFile,
      `// Overflow content for ${args.chapter} -- created by scripts/scaffold-level.mjs.
// Remember to import this chapter's *_LEVELS export from wherever the
// chapter's main file assembles its level list (see how chapter1.ts pulls
// in chapter1-extra.ts for the existing pattern).

import type { Level } from './types'
import type { SimGraph } from '@/engine/types'
import { constantTraffic } from '@/engine/traffic'
import { client } from './graphHelpers'
`,
    )
    console.log(`Created ${path.relative(process.cwd(), targetFile)}`)
  }
  appendFileSync(targetFile, skeleton)
  console.log(`Appended "${args.id}" to ${path.relative(process.cwd(), targetFile)}`)
  console.log('Remember to: add it to that file\'s exported level array, and wire that array into registry.ts if this is a new chapter file.')
}

main()
